---
- hosts: ubuntus
  become: yes
  sudo: yes

  tasks:
    - name: Copy file
      copy: src=..script.py dest=/opt/script.py  mode=755

    - name: Execute script
      command: /opt/script.py
